# Generated by Django 5.0.1 on 2026-01-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_timestamp', models.DateTimeField(verbose_name='Hora de Escaneo')),
                ('status', models.CharField(choices=[('present', 'Presente'), ('late', 'Tardanza'), ('absent', 'Falta')], max_length=20, verbose_name='Estado')),
                ('laptop_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de Laptop')),
                ('registration_method', models.CharField(choices=[('scanner', 'Escáner'), ('manual', 'Manual'), ('automatic', 'Automático')], default='scanner', max_length=20, verbose_name='Método de Registro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-scan_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DailySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Fecha')),
                ('scheduled_open_time', models.TimeField(verbose_name='Hora de Apertura Programada')),
                ('punctuality_limit', models.TimeField(verbose_name='Límite de Puntualidad')),
                ('scheduled_close_time', models.TimeField(verbose_name='Hora de Cierre Programada')),
                ('actual_open_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora Real de Apertura')),
                ('actual_close_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora Real de Cierre')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('open', 'Abierta'), ('closed', 'Cerrada')], default='pending', max_length=20, verbose_name='Estado')),
                ('total_students', models.IntegerField(default=0, verbose_name='Total de Estudiantes')),
                ('total_present', models.IntegerField(default=0, verbose_name='Total Presentes')),
                ('total_late', models.IntegerField(default=0, verbose_name='Total Tardanzas')),
                ('total_absent', models.IntegerField(default=0, verbose_name='Total Faltas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Sesión Diaria',
                'verbose_name_plural': 'Sesiones Diarias',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(max_length=100, unique=True, verbose_name='Clave')),
                ('config_value', models.TextField(verbose_name='Valor')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
    ]
