# Generated by Django 5.0.1 on 2026-01-14 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Registrado Por'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student', verbose_name='Estudiante'),
        ),
        migrations.AddIndex(
            model_name='dailysession',
            index=models.Index(fields=['date'], name='attendance__date_fc4882_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysession',
            index=models.Index(fields=['status'], name='attendance__status_88a775_idx'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.dailysession', verbose_name='Sesión'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['session'], name='attendance__session_ad8f43_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student'], name='attendance__student_018d17_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='attendance__status_132c06_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'session')},
        ),
    ]
