# Generated by Django 5.0.1 on 2026-03-30 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('students', '0002_change_sections_to_classroom_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Justification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Motivo de Justificación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Justificación')),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='justification', to='attendance.attendance', verbose_name='Asistencia')),
                ('justified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justifications_made', to=settings.AUTH_USER_MODEL, verbose_name='Justificado Por')),
            ],
            options={
                'verbose_name': 'Justificación',
                'verbose_name_plural': 'Justificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualEntryTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Conteo de Entradas Manuales')),
                ('alert_sent', models.BooleanField(default=False, verbose_name='Alerta Enviada')),
                ('last_entry_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Entrada Manual')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual_entry_tracker', to='students.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Rastreador de Entrada Manual',
                'verbose_name_plural': 'Rastreadores de Entrada Manual',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('manual_entry_alert', 'Alerta de Entrada Manual'), ('justification_limit', 'Límite de Justificaciones'), ('system', 'Sistema')], max_length=50, verbose_name='Tipo de Notificación')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('target_roles', models.JSONField(default=list, verbose_name='Roles Destino')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='attendance.dailysession', verbose_name='Sesión')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='students.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Lectura')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='attendance.notification', verbose_name='Notificación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Lectura de Notificación',
                'verbose_name_plural': 'Lecturas de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='StudentJustificationCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Conteo de Justificaciones')),
                ('last_reset_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Reinicio')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='justification_counter', to='students.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Contador de Justificaciones',
                'verbose_name_plural': 'Contadores de Justificaciones',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='attendance__notific_b339c1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='attendance__created_031d02_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationread',
            unique_together={('notification', 'user')},
        ),
    ]
