# Generated by Django 5.0.1 on 2026-03-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('director', 'Director'), ('auxiliar', 'Auxiliar'), ('psicologo', 'Psicólogo'), ('escaner', 'Escáner')], default='auxiliar', max_length=20, verbose_name='Rol'),
        ),
    ]
