# Generated by Django 5.0.1 on 2026-01-14 23:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe tener exactamente 8 dígitos', regex='^\\d{8}$')], verbose_name='DNI')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('paternal_surname', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('maternal_surname', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('grade', models.CharField(choices=[('1ro', '1ro Secundaria'), ('2do', '2do Secundaria'), ('3ro', '3ro Secundaria'), ('4to', '4to Secundaria'), ('5to', '5to Secundaria')], max_length=10, verbose_name='Grado')),
                ('section', models.CharField(max_length=5, verbose_name='Sección')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/', verbose_name='Foto')),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='barcodes/', verbose_name='Código de Barras')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['grade', 'section', 'paternal_surname', 'maternal_surname'],
                'indexes': [models.Index(fields=['dni'], name='students_st_dni_e945e0_idx'), models.Index(fields=['grade', 'section'], name='students_st_grade_7dde38_idx')],
            },
        ),
    ]
